### ISSUE TITLE
Error 24: resetStackedRules is not a function

### ISSUE THREAD

**Issue by Walt-Ponpon** [zeidanbm/Photoshop-NFT-Art-Generator#1]
Hi,
Just wanted to test your script with the .psd file provided in your package and got an error.
How to reproduce:

1. Open eyes-nft.psd in Photoshop
2. Go to File/Scripts/Browse
3. Select generate.jsx
4. Fill all requested fields plus check DNA true
5. Validate "OK"

Expected result:
Images will be generated

Current result:
Error 24: resetStackedRules is not a function
line: 151
-> resetStackedRules();

System
MacBook Pro 16 M1 Max 64 Gb
Mac OS 12.2.1
Photoshop 23.3.2

**Comment by zeidanbm** [comment]
@Walt-Ponpon I made a lot of changes to the conditions script which affected the generated script. But did not upload the latest version until now. It should work now as this function `resetStackedRules();`  is no longer used.
